x-service-templates:
  payment-processor: &payment-processor
    build:
      context: ./backend/rinha-backend-2025
      dockerfile: Dockerfile
    networks:
      - payment-processor
      - payment-processor-db
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"

  payment-processor-db: &payment-processor-db
    image: postgres:17-alpine
    networks:
      - payment-processor-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

services:
  api-processor-1:
    <<: *payment-processor
    container_name: rinha-api-processor-1
    hostname: rinha-api-processor-1
    environment:
      - TRANSACTION_FEE=0.05
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=rinha-api-db-1;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8001:8080
    depends_on:
      - api-processor-db-1

  api-processor-db-1:
    <<: *payment-processor-db
    container_name: rinha-api-db-1
    hostname: rinha-api-db-1

  api-processor-2:
    <<: *payment-processor
    container_name: rinha-api-processor-2
    hostname: rinha-api-processor-2
    environment:
      - TRANSACTION_FEE=0.15
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=rinha-api-db-2;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8002:8080
    networks:
      - payment-processor
      - payment-processor-db
    depends_on:
      - api-processor-db-2

  api-processor-db-2:
    <<: *payment-processor-db
    container_name: rinha-api-db-2
    hostname: rinha-api-db-2

networks:
  payment-processor:
    name: payment-processor
    driver: bridge
  payment-processor-db:
    driver: bridge